config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  root 'pages#home'
  get 'about', to: 'pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'


  resources :users
  resources :sessions, only: :create
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: { maximum: 140 }
  default_scope -> { order('created_at DESC')}
  mount_uploader :picture, PictureUploader
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_secure_password
  #Basic validation
  validates :name, presence: true, length: {minimum:5, maximum:50}
  #Validate email
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { minimum:5, maximum:255 },
                                    format: { with: EMAIL_REGEX },
                                    uniqueness: { case_sensitive: false }
  #Validate password
  validates :password, presence: true, length: { minimum:6 }, allow_nil: true

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  
  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy      
                                  
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower


  #follow a user
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
  #unfollow a user
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  #return true if the current user is following the other user
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  #return a users feeds
  def feed
    Micropost.where("user_id IN (?) OR user_id = ?", following.ids, id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include UsersHelper

  def logged_in_user
    unless logged_in?
      flash[:info] = "Please Login"
      redirect_to login_url
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Sucessfully saved!"
      redirect_back(fallback_location: request.referer)
    else
      render 'users/home_feed'
    end
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy
    flash[:success] = "Successfully Deleted Post!"
    redirect_back(fallback_location: request.referer)
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @microposts = current_user.feed.paginate(page: params[:page], per_page: 10)
      render 'users/home_feed'
    end
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    redirect_back(fallback_location: request.referer)
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    redirect_back(fallback_location: request.referer)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Successfully Logged in!"
      redirect_to root_url
    else
      flash[:danger] = "Invalid Credentials"
      redirect_to login_url
    end
  end

  def destroy
    log_out
    flash[:success] = "Successfully Logged out!"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: [:new, :create]
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:edit, :update, :show]

  def index
    @user = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Successfully Added"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @micropost = @user.microposts.build
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 12)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Successfully Updated"
      redirect_to root_url
    else
      render 'edit'
    end
end

def destroy
  if @user.destroy
    flash[:success] = "Successfully Deleted"
    redirect_to root_url
  else
    flash[:danger] = "Delete Failed"
    redirect_to root_url
  end
end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    @user = User.find(params[:id])
    if @user != current_user
      flash[:danger] = "You are not authorized"
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user,size)
    #Generate hex token from gravatar
    gravatar_id = Digest::MD5::hexdigest(user.email)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "rounded-circle #{size}")
  end
end

app/views/layouts/_footer.html.erb
<div id="footer" class="py-4 bg-dark text-white-50">
    <div class="container">
        <div class="row">
            <div class="col-8">
                <small>Copyright &copy; Twitter Clone</small>
            </div>
            <div class="socialmedia col-4">
                <a  href="#" class="fab fa-facebook"></a>
                <a  href="#" class="fab fa-twitter"></a>
                <a  href="#" class="fab fa-instagram"></a>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <%= link_to  "Twitter Clone", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <%= link_to  "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to  "About", about_path, class: "nav-link" %>
                </li>
                <% if logged_in? %>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <%= current_user.name %>
                            <%= gravatar_for(current_user, "profile-small")%>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
                            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
                            <%= link_to "User", users_path, class: "dropdown-item" %>
                        <div class="dropdown-divider"></div>
                            <%= link_to  "Logout", logout_path, method: :delete, class: "dropdown-item" %>
                        </div>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to  "Sign-Up", signup_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to  "Login", login_path, class: "nav-link" %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= render  "layouts/navbar" %>
        <div class="container">
            <% if flash.any? %>
                <% flash.each do |type, msg| %>
                    <div class="mt-4 alert alert-<%= type %>" role="alert">
                        <div>
                            <%= msg %>
                        </div>
                    </div>
                <% end %>
            <% end %>
            <%= yield %>
        </div>
    </body>
</html>

app/views/microposts/_form.html.erb
<%= form_for @micropost do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
        <%= f.text_area :content, size:"20x5", class:"form-control", placeholder: "Share your thoughts..."%>
    </div>
    <div class="form-group">
        <%= f.file_field :picture, accept: "image/jpeg, image/gif, image/png"%>
    </div>
    <div class="mt-2">
        <%= f.submit "Post", class: "btn btn-primary btn-block"%>
    </div>
<% end %>

app/views/microposts/_micropost.html.erb
<div class="media mb-3">
    <%= gravatar_for(micropost.user, "profile-medium") %>
    <div class="media-body ml-3">
        <h5><%= link_to micropost.user.name, micropost.user, class: "text-decoration-none"%></h5>
        <%= micropost.content %>
        <% if micropost.picture? %>
            <div>
                <%= image_tag micropost.picture.url, class: "mw-100" %>
            </div>
        <% end %>
        <div>
            <small class="text-muted">Posted <%= time_ago_in_words(micropost.created_at) %> ago </small> 
        </div>
    </div>
    <% if micropost.user == current_user %>
        <%= link_to "Remove", micropost, method: :delete,
                                          data: { confirm: "Are you sure?"},
                                          class: "float-right" %>
    <% end %>
</div>

app/views/pages/about.html.erb
<div class="jumbotron mt-4">
    <h1 class="display-4">About Twitter Clone App</h1>
    <p>This is a Ruby on Rails application.</p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron mt-4">
    <h1 class="display-4">Twitter Clone App</h1>
    <h2>Welcome to Twitter Clone!</h2>
</div>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        This for contains errors.
    </div>
    <ul>
        <% object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build do |f| %>
    <%= hidden_field_tag :followed_id, @user.id %>
    <%= f.submit "Follow", class: "btn btn-primary"%>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
        <% if current_user.following?(@user) %>
            <%= render "unfollow"%>
        <% else %>
            <%= render "follow"%>
        <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <%= render  "shared/error_messages" %>
    <div class="form-group mt-4">
        <%= f.text_field :name, class:"form-control", placeholder: "Name" %>
    </div>

    <div class="form-group">
        <%= f.email_field :email, class:"form-control", placeholder: "Email"%>
    </div>

    <div class="form-group">
        <%= f.password_field :password, class:"form-control", placeholder: "Password"%>
    </div>

    <div class="form-group">
        <%= f.password_field :password_confirmation, class:"form-control", placeholder: "Confirm Password"%>
    </div>

    <div class="actions">
        <%= f.submit btn_msg, class: "btn btn-primary btn-block" %>
    </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: @user.id),
    html: {method: :delete} do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-danger" %>
<% end %>

app/views/users/edit.html.erb
<div class="col-6 mx-auto">
    <h1 class="text-center m-4">Edit Profile</h1>
    <%= render  "form", btn_msg: "Update Profile" %>
</div>

app/views/users/home_feed.html.erb
<div class="row mt-4">
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                User Information
            </div>
            <div class="card-body text-center">
                <%= gravatar_for(current_user, "profile-medium")%>
                <h5 class="mt-2"><%= current_user.name %></h5>
                <p><%= current_user.email %></p>
            </div>
            <div class="card-footer">
                <%= render "microposts/form" %>
            </div>
        </div>
    </div>

    <div class="col-8">
        <div class="card">
            <div class="card-header">
                Activity Feed
            </div>
            <div class="card-body">
                <% if @microposts.any? %>
                    <%= render @microposts %>
                    <div class="pagination justify-content-center mt-4">
                        <%= will_paginate @microposts %>
                    </div>
                    <% else %>
                    <h4 class="text-center">There's no microposts.</h4>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<h1 class="text-center m-4">All Users</h1>
<div class="row">
    <% @user.each do |user| %>
    <div class="col-6">
        <div class="card mb-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-2">
                        <%= gravatar_for(user, "profile-meduim")%>
                    </div>
                    <div class="col-10">
                        <h6><%= link_to  user.name, user_path(user), class: "text-decoration-none" %></h6>
                        <div><%= user.email %></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>
<div class="pagination justify-content-center">
    <%= will_paginate @user%>
</div>

app/views/users/new.html.erb
<div class="col-6 mx-auto ">
    <h1 class="text-center">Sign-Up</h1>
    <hr>
    <%= render  "form", btn_msg: "Create new account" %>
</div>

app/views/users/show.html.erb
<div class="row mt-4">
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                User Information
            </div>
            <div class="card-body text-center">
                <%= gravatar_for(@user, "profile-medium")%>
                <h5 class="mt-2"><%= @user.name %></h5>
                <p><%= @user.email %></p>
            </div>
        </div>
    </div>
    <div class="col-8">
        <div class="card">
            <div class="card-header">
                Activity Feed (<%= @user.microposts.count %>)
            </div>
            <div class="card-body">
                <% if @user.microposts.any? %>
                    
                <% end %>
            </div>
        </div>
    </div>
</div>